/* Generated by pc/train.py. Do not edit by hand. */
#pragma once

/* Must match NUM_GESTURES in src/app_config.h. */
#define GESTURE_LABELS { "swipe_left", "swipe_right", "circle_cw", "circle_ccw", "vertical", "unknown" }
