#!/usr/bin/env bash
# run_tests.sh - host-side verification of the firmware.
#
# The parts of this project that can be checked without an ESP32:
#   - src/mhi.c and pc/mhi.py produce bit-identical Motion History Images
#   - the int8 quantisation mapping is the standard one
#   - src/vote.c passes its unit tests
#   - src/main.c and src/infer.cpp are syntactically valid, in every
#     combination of generated headers present
#
# The last one is not a formality. src/main.c and src/infer.cpp are the two
# files that only compile on the target, and that is exactly where mistakes
# hide: infer.cpp references C++-only TFLM types and must be a .cpp file, and
# a partial training run can leave model.h present with labels.h missing.
# Both of those were real bugs here, found by this script.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/build/tests"
# pc/parity.py looks for the harness here. It must match, or the check silently
# errors out instead of running.
PARITY_DIR="$ROOT/build/parity"
STUBS="$ROOT/tools/esp_stubs"
mkdir -p "$WORK" "$PARITY_DIR"

CFLAGS="-std=c11 -O2 -Wall -Wextra -Wconversion"
SYN_C="-std=c11 -Wall -Wextra -Wno-unused-parameter -I $STUBS -I $ROOT/src \
  -include $STUBS/esp_stubs.h"
SYN_CXX="-x c++ -std=c++17 -Wall -Wextra -Wno-unused-parameter -I $STUBS \
  -I $ROOT/src -include $STUBS/esp_stubs.h"

banner() { printf '\n== %s ==\n' "$1"; }

banner "compiling src/mhi.c and src/vote.c for the host"
gcc $CFLAGS -o "$WORK/test_vote" "$ROOT/tools/test_vote.c" "$ROOT/src/vote.c" -lm
gcc $CFLAGS -o "$PARITY_DIR/test_mhi_parity" \
    "$ROOT/tools/test_mhi_parity.c" "$ROOT/src/mhi.c"

banner "vote decoder unit tests"
"$WORK/test_vote"

banner "MHI C/Python parity and quantisation helpers"
python3 "$ROOT/pc/parity.py"

# ---------------------------------------------------------------------------
# Syntax-check the target-only translation units in every header combination.
# model.h / labels.h / golden_vector.h are generated by pc/train.py, and any
# subset can legitimately be absent.
# ---------------------------------------------------------------------------
banner "syntax-checking firmware sources"

M="$ROOT/src/model.h"
L="$ROOT/src/labels.h"
G="$ROOT/src/golden_vector.h"
BAK="$WORK/genbak"
MOCK="$ROOT/data/mock-generated"

# Back up whatever the developer actually has, because the combo loop below
# overwrites these files. Losing a real trained model to `make test` would be a
# nasty surprise.
rm -rf "$BAK"
mkdir -p "$BAK"
had_model=0
for f in "$M" "$L" "$G"; do
    if [ -f "$f" ]; then
        cp "$f" "$BAK/$(basename "$f")"
        [ "$f" = "$M" ] && had_model=1
    fi
    rm -f "$f"
done

restore() {
    for f in "$M" "$L" "$G"; do
        if [ -f "$BAK/$(basename "$f")" ]; then
            cp "$BAK/$(basename "$f")" "$f"
        else
            rm -f "$f"
        fi
    done
    rm -rf "$BAK"
}
trap restore EXIT

gen() {
    if [ -f "$MOCK/$(basename "$1")" ]; then
        cp "$MOCK/$(basename "$1")" "$1"
    fi
}

check_combo() {
    local desc="$1"
    # shellcheck disable=SC2086
    if g++ -fsyntax-only $SYN_CXX "$ROOT/src/infer.cpp" 2>"$WORK/err.txt"; then
        echo "  ok   infer.cpp [$desc]"
    else
        echo "  FAIL infer.cpp [$desc]"
        sed 's/^/         /' "$WORK/err.txt"
        return 1
    fi
    if gcc -fsyntax-only $SYN_C "$ROOT/src/main.c" 2>"$WORK/err.txt"; then
        echo "  ok   main.c  [$desc]"
    else
        echo "  FAIL main.c  [$desc]"
        sed 's/^/         /' "$WORK/err.txt"
        return 1
    fi
}

rc=0
rm -f "$M" "$L" "$G"
check_combo "no model, no labels, no golden" || rc=1

gen "$M"
check_combo "model only (labels.h missing)" || rc=1

gen "$L"
check_combo "model + labels" || rc=1

gen "$G"
check_combo "model + labels + golden (full)" || rc=1

rm -f "$M" "$L" "$G"
gen "$G"
check_combo "golden only, no model" || rc=1

# Restore first, so the tree is left exactly as it was found.
restore
trap - EXIT
if [ "$had_model" -eq 1 ]; then
    echo "  note  a trained src/model.h was present and has been restored"
else
    echo "  note  no trained model in src/ (expected before pc/train.py)"
fi

if [ "$rc" -ne 0 ]; then
    echo
    echo "firmware syntax check FAILED"
    exit 1
fi

banner "all host tests passed"
